"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthProvider";
import { usePathname } from "next/navigation";
import { checkIsPublicRoute } from "@/functions/check-routes";
import PrivateRoute from "@/routes/PrivateRoutes";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isPublic = checkIsPublicRoute(pathname);

  useEffect(() => {
    // Seu código de manipulação do DOM aqui
    const script = document.createElement("script");
    script.src = "https://cdn.jsdelivr.net/npm/@types/nookies@2.0.3/+esm";
    script.type = "module";
    document.body.appendChild(script);

    // Remova o script quando o componente for desmontado
    return () => {
      document.body.removeChild(script);
    };
  }, []);
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          {isPublic && children}

          {!isPublic && (
            <PrivateRoute pathname={pathname}>{children}</PrivateRoute>
          )}
        </body>
      </html>
    </AuthProvider>
  );
}
